### ISSUE TITLE
How to plot the weights of the neural network

### ISSUE THREAD

**Issue by olixu** [enajx/HebbianMetaLearning#1]
Thanks for your nice work!

But, how to plot the weights of the neural network in the paper(Figure1), the image is just like a QR code.

Can you tell me how or give me some key words to search for google?

**Comment by enajx** [comment]
You can simply use matplotlib to create the 3 subplots and then use imshow to display the weights.

**Comment by olixu** [comment]
> You can simply use matplotlib to create the 3 subplots and then use imshow to display the weights.

But how to draw this type of weights.
![weights of the neural network](https://user-images.githubusercontent.com/16973063/94357147-bb6c0100-0085-11eb-81a5-c94d53668a74.PNG)

**Comment by enajx** [comment]
You get those images by plotting the network's weights at different timesteps during the evaluation of the agent.

**Comment by olixu** [comment]
> You get those images by plotting the network's weights at different time steps during the evaluation of the agent.

Hello, but what I mean is that this fig is using white and black pixels while the weights of the neural network are just a digital, so how to convert digital to pixels?

May I can convert the digital {-1~1} to the gray pixel {-255, 255}? However, the limitations of the weights of the network is unknown.

Thank you .

**Comment by enajx** [comment]
You can find the documentation on how to use matplotlib imshow here: https://matplotlib.org/api/_as_gen/matplotlib.pyplot.imshow.html

**Comment by olixu** [comment]
> You can find the documentation on how to use matplotlib imshow here: https://matplotlib.org/api/_as_gen/matplotlib.pyplot.imshow.html

I am sorry that because I am not caring about the implementation of something. 

I am caring about how I get the image, not the implementation.

BTW, are you the author of the paper?
