### ISSUE TITLE
Facing out of bound array error

### ISSUE THREAD

**Issue by triakshunn** [enajx/HebbianMetaLearning#6]
I am trying to reproduce the results of the Car Racing task
When I do `python train_hebb.py --environment CarRacing-v2 `
I get the following error:
![image](https://user-images.githubusercontent.com/35093460/229374996-8fbee12b-8d93-4bc5-838e-008ed4dea308.png)

**Comment by enajx** [comment]
It might be related to the packages version, try using the ones indicated here: https://github.com/enajx/HebbianMetaLearning/issues/5#issuecomment-1297662935

**Comment by triakshunn** [comment]
Okay it works for these package versions. Thanks!
