### ISSUE TITLE
Error when trying to run gym tasks

### ISSUE THREAD

**Issue by triakshunn** [enajx/HebbianMetaLearning#7]
When I try to run the repo on the Cartpole v1 gym task by `python train_hebb.py --environment CartPole-v1`,I get the following error:
![image](https://user-images.githubusercontent.com/35093460/229375135-2ee1684b-5efb-41da-b19c-52c060d8dc70.png)

**Comment by enajx** [comment]
It might be related to the packages version, try using the ones indicated here: https://github.com/enajx/HebbianMetaLearning/issues/5#issuecomment-1297662935

**Comment by triakshunn** [comment]
Yeah the repo works for these package versions. Thanks!
